// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ResourceAllocation.DataLayer;

namespace ResourceAllocation.DataLayer.Migrations
{
    [DbContext(typeof(ResourceAllocationDbContext))]
    partial class ResourceAllocationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.14-servicing-32113")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("ResourceAllocation.Domain.Artist", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("BreastSize");

                    b.Property<DateTime>("DateCreated");

                    b.Property<string>("Description");

                    b.Property<string>("EyesColor");

                    b.Property<string>("Facebook");

                    b.Property<string>("Gender");

                    b.Property<string>("HairColor");

                    b.Property<int>("Height");

                    b.Property<int>("HipsSize");

                    b.Property<string>("Instagram");

                    b.Property<string>("Name");

                    b.Property<string>("Photo");

                    b.Property<int>("WaistSize");

                    b.Property<int>("Weight");

                    b.HasKey("Id");

                    b.ToTable("Artists");
                });

            modelBuilder.Entity("ResourceAllocation.Domain.Designer", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("DateCreated");

                    b.Property<DateTime>("DateTimeShow");

                    b.Property<string>("LocationShow");

                    b.Property<string>("Mail");

                    b.Property<string>("Name");

                    b.Property<string>("Surname");

                    b.Property<int>("nrOfArtistsNeeded");

                    b.HasKey("Id");

                    b.ToTable("Designers");
                });

            modelBuilder.Entity("ResourceAllocation.Domain.DesignerArtists", b =>
                {
                    b.Property<Guid>("ArtistId");

                    b.Property<Guid>("DesignerId");

                    b.Property<int>("Order");

                    b.HasKey("ArtistId", "DesignerId");

                    b.HasIndex("DesignerId");

                    b.ToTable("DesignerArtists");
                });

            modelBuilder.Entity("ResourceAllocation.Domain.DesignerArtists", b =>
                {
                    b.HasOne("ResourceAllocation.Domain.Artist", "Artist")
                        .WithMany("FavoriteForDesigners")
                        .HasForeignKey("ArtistId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("ResourceAllocation.Domain.Designer", "Designer")
                        .WithMany("FavoriteArtists")
                        .HasForeignKey("DesignerId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
